swagger: "2.0"
info:
  version: "1.1"
  title: skillrary api
  description: this is api docs
  termsOfService: terms
  contact:
    name: arun
    url: http://localhost:5000
    email: arun@gmail.com
  license:
    name: MIT
    url: http:localhost:5000
schemes: [http,https]
paths:
  /auth/register:
    post:
      summary: post request for register user 
      description: register check usin params
      parameters: 
        - in: query
          name: username
          type: string
          required: true
        - in: query
          name: password
          type: string
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
   
  
  
  
